import Link from "next/link";
import prisma from "@/lib/prisma";
import { AdminBadge } from "@/components/admin/admin-badge";
import { formatDate, formatRelativeTime } from "@/lib/admin-utils";

function MetricIcon({ color, children }: { color: string; children: React.ReactNode }) {
  return (
    <div className={`flex h-11 w-11 items-center justify-center rounded-full ${color}`}>
      <div className="h-5 w-5 text-white">{children}</div>
    </div>
  );
}

export default async function AdminDashboardPage() {
  const [totalInquiries, newInquiries, publishedPosts, activePrograms, recentInquiries, recentPosts, recentPrograms, recentEvents] =
    await Promise.all([
      prisma.inquiry.count(),
      prisma.inquiry.count({ where: { status: "NEW" } }),
      prisma.blogPost.count({ where: { status: "PUBLISHED" } }),
      prisma.program.count({ where: { status: { in: ["ACTIVE", "UPCOMING"] } } }),
      prisma.inquiry.findMany({
        orderBy: { createdAt: "desc" },
        take: 5,
      }),
      prisma.blogPost.findMany({
        orderBy: { updatedAt: "desc" },
        select: { id: true, title: true, updatedAt: true },
        take: 5,
      }),
      prisma.program.findMany({
        orderBy: { updatedAt: "desc" },
        select: { id: true, name: true, updatedAt: true },
        take: 5,
      }),
      prisma.event.findMany({
        orderBy: { updatedAt: "desc" },
        select: { id: true, name: true, updatedAt: true },
        take: 5,
      }),
    ]);

  const recentActivity = [
    ...recentPosts.map((item) => ({ id: item.id, title: item.title, type: "Blog Post", updatedAt: item.updatedAt })),
    ...recentPrograms.map((item) => ({ id: item.id, title: item.name, type: "Program", updatedAt: item.updatedAt })),
    ...recentEvents.map((item) => ({ id: item.id, title: item.name, type: "Event", updatedAt: item.updatedAt })),
  ]
    .sort((a, b) => b.updatedAt.getTime() - a.updatedAt.getTime())
    .slice(0, 5);

  return (
    <div className="space-y-6">
      <section className="grid gap-4 xl:grid-cols-4">
        <MetricCard
          label="Total Inquiries"
          value={totalInquiries}
          icon={
            <MetricIcon color="bg-[#0F2447]">
              <svg viewBox="0 0 24 24" className="h-5 w-5 fill-none stroke-current stroke-2">
                <path d="M4 6h16" />
                <path d="M4 12h16" />
                <path d="M4 18h10" />
              </svg>
            </MetricIcon>
          }
        />
        <MetricCard
          label="New Inquiries"
          value={newInquiries}
          icon={
            <MetricIcon color="bg-[#D97706]">
              <svg viewBox="0 0 24 24" className="h-5 w-5 fill-none stroke-current stroke-2">
                <path d="M12 3v18" />
                <path d="M3 12h18" />
              </svg>
            </MetricIcon>
          }
        />
        <MetricCard
          label="Published Posts"
          value={publishedPosts}
          icon={
            <MetricIcon color="bg-[#16A34A]">
              <svg viewBox="0 0 24 24" className="h-5 w-5 fill-none stroke-current stroke-2">
                <path d="M7 3h7l5 5v13H7z" />
                <path d="M14 3v5h5" />
              </svg>
            </MetricIcon>
          }
        />
        <MetricCard
          label="Active Programs"
          value={activePrograms}
          icon={
            <MetricIcon color="bg-[#6B7280]">
              <svg viewBox="0 0 24 24" className="h-5 w-5 fill-none stroke-current stroke-2">
                <path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v15.5A2.5 2.5 0 0 0 17.5 16H4z" />
                <path d="M4 5.5V19a2 2 0 0 0 2 2h12" />
              </svg>
            </MetricIcon>
          }
        />
      </section>

      <section className="grid gap-6 xl:grid-cols-[1.3fr_0.7fr]">
        <div className="admin-card p-6">
          <div className="flex items-center justify-between gap-4">
            <div>
              <h2 className="text-lg font-semibold text-[#0F2447]">Recent Inquiries</h2>
              <p className="mt-1 text-sm text-[#4B5563]">The latest leads generated by the public website.</p>
            </div>
            <Link href="/admin/inquiries" className="text-sm font-semibold text-[#0F2447]">
              View All
            </Link>
          </div>

          <div className="mt-6">
            {recentInquiries.length === 0 ? (
              <div className="admin-empty-state">
                <div className="text-base font-semibold text-[#0F2447]">No inquiries yet</div>
                <p className="text-sm text-[#4B5563]">New contact form submissions will appear here.</p>
              </div>
            ) : (
              <div className="divide-y divide-[#EEEEEE]">
                {recentInquiries.map((inquiry) => (
                  <div key={inquiry.id} className="flex items-start justify-between gap-4 py-4">
                    <div className="min-w-0 flex-1">
                      <div className="text-sm font-semibold text-[#0F2447]">{inquiry.name}</div>
                      <div className="mt-1 text-[13px] text-[#1F2937]/60">{inquiry.email}</div>
                      {inquiry.serviceOfInterest ? (
                        <div className="mt-3">
                          <span className="rounded-full bg-[#F0EDE6] px-3 py-1 text-xs font-medium text-[#0F2447]">
                            {inquiry.serviceOfInterest}
                          </span>
                        </div>
                      ) : null}
                    </div>
                    <div className="space-y-2 text-right">
                      <div className="text-xs text-[#1F2937]/40">{formatDate(inquiry.createdAt)}</div>
                      <AdminBadge status={inquiry.status} />
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="admin-card p-6">
          <h2 className="text-lg font-semibold text-[#0F2447]">Quick Actions</h2>
          <div className="mt-6 space-y-3">
            <QuickAction href="/admin/blog/new" label="New Blog Post" />
            <QuickAction href="/admin/programs/new" label="Add Program" />
            <QuickAction href="/admin/events/new" label="Add Event" />
            <QuickAction href="/admin/announcements/new" label="Add Announcement" />
          </div>
        </div>
      </section>

      <section className="admin-card p-6">
        <div className="flex items-center justify-between gap-4">
          <div>
            <h2 className="text-lg font-semibold text-[#0F2447]">Recent Activity</h2>
            <p className="mt-1 text-sm text-[#4B5563]">The latest content edits across posts, programs, and events.</p>
          </div>
        </div>

        <div className="mt-6 divide-y divide-[#EEEEEE]">
          {recentActivity.map((item) => (
            <div key={`${item.type}-${item.id}`} className="flex items-center justify-between gap-4 py-4">
              <div>
                <div className="text-sm font-semibold text-[#0F2447]">{item.title}</div>
                <div className="mt-1 text-[13px] text-[#1F2937]/60">{item.type}</div>
              </div>
              <div className="text-sm text-[#1F2937]/50">{formatRelativeTime(item.updatedAt)}</div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}

function MetricCard({
  icon,
  label,
  value,
}: {
  icon: React.ReactNode;
  label: string;
  value: number;
}) {
  return (
    <div className="admin-card p-5">
      <div className="flex items-start justify-between gap-4">
        <div>
          <div className="font-[family:var(--font-playfair)] text-4xl text-[#0F2447]">{value}</div>
          <div className="mt-3 text-xs uppercase tracking-[0.18em] text-[#1F2937]/60">{label}</div>
        </div>
        {icon}
      </div>
    </div>
  );
}

function QuickAction({ href, label }: { href: string; label: string }) {
  return (
    <Link href={href} className="admin-button-primary h-11 w-full justify-center rounded-[12px]">
      {label}
    </Link>
  );
}
